// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Author struct {
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	Papers    []*Paper   `json:"papers"`
	Psuedonym *bool      `json:"psuedonym"`
	CreateAt  *time.Time `json:"createAt"`
}

type CreateAuthorInput struct {
	Name      string `json:"name"`
	Psuedonym *bool  `json:"psuedonym"`
}

type CreateCurrencyInput struct {
	Name   string `json:"name"`
	Ticker string `json:"ticker"`
}

type CreateFileInput struct {
	CoverImage *string  `json:"coverImage"`
	Source     *string  `json:"source"`
	URL        *string  `json:"url"`
	Version    *float64 `json:"version"`
}

type CreatePaperInput struct {
	Title       string  `json:"title"`
	Description *string `json:"description"`
	Excerpt     *string `json:"excerpt"`
	PageNum     *int    `json:"pageNum"`
}

type CreateUserInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Currency struct {
	ID       string     `json:"id"`
	Name     string     `json:"name"`
	Ticker   string     `json:"ticker"`
	CreateAt *time.Time `json:"createAt"`
}

type File struct {
	ID         string     `json:"id"`
	CoverImage *string    `json:"coverImage"`
	PubDate    *time.Time `json:"pubDate"`
	Source     *string    `json:"source"`
	URL        string     `json:"url"`
	Version    *float64   `json:"version"`
	CreateAt   *time.Time `json:"createAt"`
}

type Paper struct {
	ID          string      `json:"id"`
	Author      []*Author   `json:"author"`
	Currency    []*Currency `json:"currency"`
	Description *string     `json:"description"`
	Excerpt     *string     `json:"excerpt"`
	File        []*File     `json:"file"`
	PageNum     *int        `json:"pageNum"`
	Title       string      `json:"title"`
	CreateAt    *time.Time  `json:"createAt"`
}

type UpdateAuthorInput struct {
	Name      *string `json:"name"`
	Psuedonym *bool   `json:"psuedonym"`
}

type UpdateCurrencyInput struct {
	Name   *string `json:"name"`
	Ticker *string `json:"ticker"`
}

type UpdateFileInput struct {
	CoverImage *string  `json:"coverImage"`
	Source     *string  `json:"source"`
	URL        *string  `json:"url"`
	Version    *float64 `json:"version"`
}

type UpdatePaperInput struct {
	Title       *string `json:"title"`
	Description *string `json:"description"`
	Excerpt     *string `json:"excerpt"`
	PageNum     *int    `json:"pageNum"`
}

type UpdateUserInput struct {
	Name     *string `json:"name"`
	Email    *string `json:"email"`
	Password *string `json:"password"`
}

type User struct {
	ID       string     `json:"id"`
	Email    string     `json:"email"`
	Name     string     `json:"name"`
	Password string     `json:"password"`
	CreateAt *time.Time `json:"createAt"`
}
